.deploy_composer:
  stage: deploy
  script:
    - echo $COMPOSE_PATH
    - mkdir -p $COMPOSE_PATH 
    - cp -a . $COMPOSE_PATH
    - echo "Composer actualizado "$COMPOSE_PATH

.deploy_composer_snapshot:
  extends: .deploy_composer
  environment:
    name: SNAPSHOT  
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /(.*)SNAPSHOT$/'
      when: manual

.deploy_composer_release:
  extends: .deploy_composer
  environment:
    name: RELEASE  
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /(.*)RELEASE$/'
      when: manual      

.deploy_composer_master:
  extends: .deploy_composer
  environment:
    name: master  
  rules:
    - if: '$CI_COMMIT_BRANCH =="master"'
      when: manual  